# fly.toml app configuration file generated for combo-breakdown-server on 2023-08-23T16:11:55+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "combo-breakdown-server"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
